import { randomBytes } from 'node:crypto';

export function loginPage(configured = true) {
  const nonce = randomBytes(16).toString('base64');
  const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Portal Celina · Ingresar</title><style nonce="${nonce}">
:root{color-scheme:light;--bg:#f4f7fb;--card:#fff;--text:#162d45;--muted:#60758b;--line:#dbe5ef;--input:#f5f8fc;--accent:#087c91}html[data-theme=dark]{color-scheme:dark;--bg:#09111f;--card:#111e30;--text:#f0f6fc;--muted:#a9bbce;--line:#344960;--input:#152438;--accent:#72dddf}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 25% 10%,var(--input),transparent 60%),var(--bg);color:var(--text);font-family:Inter,'Segoe UI',system-ui,sans-serif;min-height:100dvh;display:grid;place-items:center;padding:24px}.card{width:100%;max-width:430px;background:var(--card);border:1px solid var(--line);border-radius:22px;padding:36px;box-shadow:0 12px 50px #0a294410}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.brand{display:grid;place-items:center;width:45px;height:45px;background:linear-gradient(135deg,#1551a0,#069caa);color:white;border-radius:13px;font-size:26px;font-weight:700}select{background:var(--input);color:var(--text);border:1px solid var(--line);border-radius:8px;padding:8px}.eyebrow{font-size:10px;font-weight:700;letter-spacing:.13em;color:var(--accent)}h1{font-size:29px;letter-spacing:-.04em;margin:12px 0}p{font-size:13px;line-height:1.7;color:var(--muted)}form{margin-top:26px}label{font-size:12px;font-weight:600}input{display:block;width:100%;background:var(--input);color:var(--text);border:1px solid var(--line);padding:13px;border-radius:10px;margin:9px 0 18px;font:inherit}button{width:100%;padding:13px;border:0;border-radius:10px;background:#116bab;color:white;font:600 13px Inter,'Segoe UI',sans-serif;cursor:pointer}button:disabled{opacity:.6;cursor:wait}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}small{display:block;color:var(--muted);font-size:10px;margin-top:24px}#error{color:var(--text);font-size:12px;margin:16px 0 0} @media(max-width:450px){.card{padding:28px}input{font-size:16px}}
</style></head><body><main class="card"><div class="top"><div class="brand" aria-hidden="true">C</div><select aria-label="Tema de apariencia" id="theme"><option value="light">Claro</option><option value="dark">Oscuro</option><option value="system">Automático</option></select></div><p class="eyebrow">CELINA · GESTIÓN COMERCIAL</p><h1>Bienvenido al portal</h1><p>Tu espacio de gestión. Ingresa con tu contraseña para continuar.</p><form id="login"><label for="password">Contraseña</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256" ${configured ? '' : 'disabled'}><button type="submit" ${configured ? '' : 'disabled'}>Ingresar</button><p id="error" role="alert">${configured ? '' : 'El acceso está pendiente de configuración en Vercel.'}</p></form><small>Portal Celina V4.0 · Acceso personal</small></main><script nonce="${nonce}">
const selector=document.getElementById('theme');const media=matchMedia('(prefers-color-scheme: dark)');try{const stored=localStorage.getItem('celina.theme');selector.value=['light','dark','system'].includes(stored)?stored:'system'}catch{selector.value='system'}function apply(){document.documentElement.dataset.theme=selector.value==='system'?(media.matches?'dark':'light'):selector.value}apply();selector.addEventListener('change',()=>{apply();try{localStorage.setItem('celina.theme',selector.value)}catch{}});media.addEventListener('change',apply);
document.getElementById('login').addEventListener('submit',async event=>{event.preventDefault();const field=document.getElementById('password');const button=event.target.querySelector('button');const error=document.getElementById('error');button.disabled=true;button.textContent='Verificando…';error.textContent='';try{const result=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:'login',password:field.value})});field.value='';if(result.ok){location.replace('/');return}const data=await result.json();error.textContent=data.error||'No se pudo ingresar. Intenta nuevamente.'}catch{error.textContent='No se pudo conectar. Intenta nuevamente.'}finally{button.disabled=false;button.textContent='Ingresar'}});
</script></body></html>`;
  return { html, headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'private, no-store', 'Vercel-CDN-Cache-Control': 'no-store', 'Content-Security-Policy': `default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin' } };
}
